Update dependencies to latest and adopt ProjectV2 API
Because there's an error:

```
GraphqlResponseError: Request failed due to following response errors:
 - The `ProjectNext` API is deprecated in favour of the more capable `ProjectV2` API. Follow the ProjectV2 guide at https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/, to find a suitable replacement.
```